name: react-infinite-scroll-component

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1

      - name: install dependencies
        run: yarn

      - name: lint
        run: yarn lint

      - name: prettier
        run: yarn prettier:check

      - name: unit tests
        run: yarn test

      - name: ts type checks
        run: yarn ts-check

      - uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5.5.4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./coverage/lcov.info
